"""empty message

Revision ID: 056d321f6ca8
Revises: 5a58245c1dfd
Create Date: 2023-06-13 22:46:21.724763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056d321f6ca8'
down_revision = '5a58245c1dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('titulo', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=2000), nullable=True),
    sa.Column('date_task', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    # ### end Alembic commands ###
